### ISSUE TITLE
Nume proiect

### ISSUE THREAD

**Issue by mcdobr** [mcdobr/itp#1]
Vă rog o idee de nume șmecher pentru site.

**Comment by iftodimihail** [comment]
Vreti ceva gen IMDb(Internet Movie Database) - adica sa ne facem si noi o abreviere la ceva sau nume nume?

**Comment by mcdobr** [comment]
aș zice un nume calumea, nu abreviere.

**Comment by mcdobr** [comment]
GreasyPopcorn, natChoMovie

**Comment by iftodimihail** [comment]
GreasyPopcorn mie imi place

**Comment by mcdobr** [comment]
Rămâne GreasyPopcorn.
