### ISSUE TITLE
Diagrame UML de componente

### ISSUE THREAD

**Issue by mcdobr** [mcdobr/itp#10]

**Comment by Paul-Cristian** [comment]
![uml-componente](https://user-images.githubusercontent.com/36604394/37363336-50338e32-2700-11e8-8f35-bba57f76c90a.png)

**Comment by Paul-Cristian** [comment]
Uml-ul descrie interactiunea dintre componente. Interactiunea, dupa cum se observa si in diagrama, este bidirectionala. Aceste asocieri(interactiuni) specifică o relaţie de colaborare între două componente fără a intra în detalii cu privire la interfeţele expuse sau cele folosite.

**Comment by iftodimihail** [comment]
Diacritice

Pe 13 mar. 2018 21:00, "Paul-Cristian" <notifications@github.com> a scris:

**Comment by mcdobr** [comment]
Poți să le lași doar alb pe negru. Alea albastre închis nu se văd deloc.
