### ISSUE TITLE
Diagrame UML de activitate

### ISSUE THREAD

**Issue by mcdobr** [mcdobr/itp#11]

**Comment by CIulius** [comment]
E pe foaie si ati vazut-o. O desenez in seara asta.

**Comment by CIulius** [comment]
Activity Diagram reprezintă o modalitate de modelare vizuală a fluxurilor. Cu ajutorul activity diagram pot fi modelate foarte bine use case-urile. În privinţa notaţiilor, acestea sunt foarte asemănătoare cu cele din state diagram, deoarece activity diagram nu sunt altceva decât o variaţie a state diagram.
