### ISSUE TITLE
Scurtă analiză a tipurilor de aplicații existente din perspectiva temei alese

### ISSUE THREAD

**Issue by mcdobr** [mcdobr/itp#4]

**Comment by iftodimihail** [comment]
Mine

**Comment by iftodimihail** [comment]
Trei dintre cele mai populare website-uri de recenzii de filme sunt iMDB, Rotten Tomatoes și Metacritic.
Toate aceste ofera posibilitatea unui utilizator de a oferi un rating... to be continued pentru ca nu am inspiratie deloc cand vine vorba de scris
