### ISSUE TITLE
Descrierea generală a implementării (caracteristici așteptate de la aplicație)

### ISSUE THREAD

**Issue by mcdobr** [mcdobr/itp#5]

**Comment by Paul-Cristian** [comment]
Ne dorim ca aplicația să ofere următoarele facilități de bază: căutare de filme și adăugarea de recenzii. Înregistrarea este opțională, totuși, doar membrii înregistrați pot scrie recenzii, să le editeze sau să le șteargă și să acorde o notă filmului. Vizitatorii, spre deosebire de membrii înregistrați, pot doar să caute informații pe site, în legătură cu anumite filme. Moderatorii pot adăuga atât filmele cât și informațiile despre acestea și de asemenea au posibilitatea de a suprima comentariile care nu respectă regulile comunității.
