### ISSUE TITLE
Resursele hardware/software utilizate

### ISSUE THREAD

**Issue by mcdobr** [mcdobr/itp#6]

**Comment by Paul-Cristian** [comment]
Resursele hardware/software utilizate:
- Laptop/Desktop;
- Sistem de operare : Linux, Windows;
- Eclipse Oxygen;
- Notepad++;
- Dia - Software de creare diagrame UML și ER;
- Server pentru baza de date(MySQL)
- Server web (Servlet);
- Server web pentru servicii de tip REST;
- Browser: Mozilla Firefox, Google Chrome;
- GitHub(sistem de versionare);

**Comment by mcdobr** [comment]
trebuie schimbat GitHub în Git și adaugate si alte browsere (opera, IE, Edge) dar e ok.
