### ISSUE TITLE
Diagrame UML de use-case

### ISSUE THREAD

**Issue by mcdobr** [mcdobr/itp#8]

**Comment by iftodimihail** [comment]
Mine

**Comment by iftodimihail** [comment]
[useCase.pdf](https://github.com/mcdobr/itp/files/1803334/useCase.pdf)

**Comment by iftodimihail** [comment]
![image](https://user-images.githubusercontent.com/33319632/37292282-46b4d18c-2619-11e8-9490-7733ecd3384c.png)

**Comment by iftodimihail** [comment]
![usecase](https://user-images.githubusercontent.com/33319632/37468833-a00c0b38-286c-11e8-854a-13f1f3fbf264.png)

**Comment by iftodimihail** [comment]
Vizitatorul poate doar să caute și să citească detalii despre un film.
Spre deosebire de un vizitator, un utilziator poate și să scrie o recenzie depre un anumit film.
Moderatorul este cel ce administrează conținutul platformei și moderează comentariile ( în cazul în care acestea nu corespund cu regulile comunității ).
