### ISSUE TITLE
Diagrame UML de information flow

### ISSUE THREAD

**Issue by mcdobr** [mcdobr/itp#9]

**Comment by iftodimihail** [comment]
Mine

**Comment by iftodimihail** [comment]
![informationflow](https://user-images.githubusercontent.com/33319632/37480576-41039a72-2888-11e8-9b4c-49471089d6ce.png)

**Comment by iftodimihail** [comment]
În urma căutării unui film, utilizatorul face o cerere către serverul web pentru a obține detalii despre un film. Serverul web face o cerere către serverul de servicii web, care la rândul său trimite o cerere de căutare în baza de date pentru filmul dorit. Baza de date trimite înapoi răspuns cu filmul găsit, iar serverul de servicii trimite răspunsul acestuia către serverul web într-un format de tip JSON.
În final, serverul web trimite către browser un răspuns (o pagină web) cu detalii despre film.
